language: node_js
node_js:
  - 12

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false --code-coverage --browsers ChromeHeadless
  - ng build --prod

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

notifications:
  email:
    on_failure: always
    on_success: always
