language: node_js
node_js:
  - 12

branches:
  only:
    - master

addons:
  chrome: stable
  sonarcloud:
    organization: ${SONARCLOUD_ORGANIZATION}
    token:
      secure: 'kRT+v4uQlxYXgSdE8oPReYSO8kYPQ7gGm5AOIZT9BKUebFuTiOdaRFzYftFPiTrFICo6DY+en0OWVdDJMqhEZnMt50iWowcn3/qtpaDA0iPfCC697tahBx7+gf7SvmeJrYSdybXtvHH0/FKbF9KNaLo+x+sa3istFj2K589SwKALVA82//IsMgDddDvZcvLIMYtOAwrxj2OGZc3w+djpjmkpa8BKKmIOUe+RVq4wytKYlESmTyZ4t97/LEPRfJu0LxDJwjUSQ7ki2JsJBGEocnihRqHOYsc+FUTVyNNFcm1yDYQWsSwQp6p/B8Kv+2GVjblTn63sAWac3KK5qUpMpNXiJl12jC256GAyGgNqh6LnJ022Nc4wxQMf9pR/zke21+16G3Ega6tci2irD5UzpqxsGRt4u+4jZHi3cRQcuIFK/FYBf+5TlISbpGJoRhYMHOV5stLYaj6qOB5y1pJe3K00nfAMB7GYE8xBebE4gtRwHXa7E53kueiHENVB7+njVrnzgwZqjHneoR+4IoPujnE8aKXxmnDRWj8erPOx1bcklLiw0Gp+CNvy8+r88eD7ZWen6J6ZQIubgfTYuXXXFXUm5mqFKOLxAL5fP2MI/QhdnU3S1pn1MosnNNfMVAeABfbLV/xiKFHT6+Zeey2ORpwN0SXEPoyiCIrddKRojmc='

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false --code-coverage --browsers ChromeHeadless
  - sonar-scanner
  - ng build --prod

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

notifications:
  email:
    on_failure: always
    on_success: always
